apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: backend-service
  ports:
    - port: 3000
      targetPort: 3000
      name: 'http-port'
---
apiVersion: v1
kind: Service
metadata:
  name: live-cluster-ip-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    component: backend-service
  ports:
    - port: 7070
      targetPort: 7070
      name: 'clients-websocket-port'
    - port: 7071
      targetPort: 7071
      name: 'admins-websocket-port'
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: adminpanel-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: adminpanel-service
  ports:
    - port: 5010
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pwa-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: pwa-service
  ports:
    - port: 5011
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mongo-express
  ports:
    - port: 5012
      targetPort: 8081
