apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-nginx-deployment
  labels:
    component: route-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: route-nginx
  template:
    metadata:
      labels:
        component: route-nginx
    spec:
      volumes:
        - name: var-cache
        - name: etc
        - name: var-log
        - name: var-run
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
        - name: route-nginx
          image: nginx:latest
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 128M
              cpu: 200m
              ephemeral-storage: 100M
            requests:
              memory: 128M
              cpu: 200m
              ephemeral-storage: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: route-nginx-ip-service
spec:
  type: ClusterIP
  selector:
    component: route-nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
         limit_req_zone $binary_remote_addr zone=ip_limit:10m rate=3r/s;
         server {
           listen       80;

               location /live/admin {
                    proxy_read_timeout 86400s;
                    proxy_send_timeout 86400s;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $host;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_pass http://live-cluster-ip-service:7071;

                    limit_req zone=ip_limit burst=5;
               }

               location /live {
                    proxy_read_timeout 86400s;
                    proxy_send_timeout 86400s;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $host;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_pass http://live-cluster-ip-service:7070;

                    limit_req zone=ip_limit burst=5;
               }

                location /api {
                    client_max_body_size 50M;
                    rewrite  ^/api/(.*) /$1 break;
                    proxy_pass http://backend-cluster-ip-service:3000/;

                    limit_req zone=ip_limit burst=5;
                }
           }
     }

